# Generated by Django 4.0.2 on 2022-02-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedAppParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supportedapp')),
                ('param_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.riskparam')),
            ],
        ),
        migrations.CreateModel(
            name='RiskRecomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('param_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.riskparam')),
            ],
        ),
    ]
